 
 export const Tabdata=['Categories','Latest','Papular','Featured','Ranked'];
 const rand=()=>Math.floor(Math.random() * (1000 - 1) + 1);
 export const ImageData=[
     { 
         id:rand(),
         image:`https://picsum.photos/id/${rand()}/200/300`,
         views:544,
         isLiked:1,
     },
     { 
         id:rand(),
         image:`https://picsum.photos/id/${rand()}/200/300`,
         views:544,
         isLiked:1,
     },
     { 
         id:rand(),
         image:`https://picsum.photos/id/${rand()}/200/300`,
         views:544,
         isLiked:0,
     },
     { 
         id:rand(),
         image:`https://picsum.photos/id/${rand()}/200/300`,
         views:544,
         isLiked:1,
     },
     { 
         id:rand(),
         image:`https://picsum.photos/id/${rand()}/200/300`,
         views:544,
         isLiked:0,
     },
     { 
         id:rand(),
         image:`https://picsum.photos/id/${rand()}/200/300`,
         views:544,
         isLiked:0,
     },
     { 
         id:rand(),
         image:`https://picsum.photos/id/${rand()}/200/300`,
         views:544,
         isLiked:1,
     },
     { 
         id:rand(),
         image:`https://picsum.photos/id/${rand()}/200/300`,
         views:544,
         isLiked:0,
     },
     { 
         id:rand(),
         image:`https://picsum.photos/id/${rand()}/200/300`,
         views:544,
         isLiked:0,
     },
     { 
         id:rand(),
         image:`https://picsum.photos/id/${rand()}/200/300`,
         views:544,
         isLiked:1,
     },
     { 
         id:rand(),
         image:`https://picsum.photos/id/${rand()}/200/300`,
         views:544,
         isLiked:0,
     },
     { 
        id:rand(),
        image:`https://picsum.photos/id/${rand()}/200/300`,
        views:544,
        isLiked:0,
    },
     ]